### ISSUE TITLE
Possible to modify this to pull in variables from libraries?

### ISSUE THREAD

**Issue by andrewmillen** [lorenzwoehr/link-spacing-variables#1]
Figma offers [getAvailableLibraryVariableCollectionsAsync()](https://www.figma.com/plugin-docs/api/properties/figma-teamlibrary-getavailablelibraryvariablecollectionsasync/), so seems like it might be possible.

I attempted to get it working with a fork of this repo but am not well-versed in enough in JS to get it done.

**Comment by andylikh** [comment]
Yes, please! this is very much required for this plugin to be used in actual use cases. 

Otherwise, we'll have to paste the screens into the library? Which is not practical for obvious reasons

**Comment by lorenzwoehr** [comment]
Thank you for your patience. I just released a new version that finally makes library variable collections available.

Also: Frame width, height and corner radii can now also be linked. Please use the variable scoping within the variable collection to choose which of these you'd like to link. Per default everything will be linked.
