### ISSUE TITLE
Frame radius does not match

### ISSUE THREAD

**Issue by sedatcakir** [lorenzwoehr/link-spacing-variables#3]
frame cannot find and match the given radius variable value. Can any improvements be made in this regard? Thank you very much.

**Comment by lorenzwoehr** [comment]
I couldn't replicate the issue. Could you check whether the variable scope includes "Corner radius"?

<img width="917" alt="Bildschirmfoto 2024-07-03 um 15 46 05" src="https://github.com/lorenzwoehr/link-spacing-variables/assets/5892374/ecc90f8a-9e1a-4c06-95b7-e880d4553950">
 
Does it not link just on a particular type of layer (e.g. a component instance)?

Please also double check if the variable modes are matching on the selected frame and variable collection and that you selected the correct variable collection in the plugin settings.
